sudo: required
services:
  - docker
before_install: # commands to run on the container running the installation
  # use the encrypted file uploaded to travis to connect with the service account
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in serviceaccount.json.enc -out serviceaccount.json -d 
  - curl https://sdk.cloud.google.com | bash > /dev/null; # install gcloud sdk
  - source $HOME/google-cloud-sdk/bash.path.inc # add gcloud to the path using the shell script
  - gcloud components update kubectl # gcloud to install kubectl
  - gcloud auth activate-service-account --key-file service-account.json #authorize the service account
